<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function getAppsWithAdverts($limit)
    {
        $qb = $this->createQueryBuilder('a')
            ->join('a.advert', 'advs')
            ->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }
}
